version: '3.1'

services:
  server:
    env_file:
      - ./.env
    build: .
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
volumes:
  database_data:
    driver: local
