version: '3.1'

services:
  server:
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://postgres:5432/summhub_prod
      DATABASE_USER: "summhub"
      DATABASE_PASSWORD: "summhub"
      DATABASE_HOST: "0.0.0.0"
    build: .
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "summhub"
      POSTGRES_USER: "summhub"
      POSTGRES_DB: "summhub_prod"
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
