version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Decode Env File
          command: echo ${ENV_FILE} | base64 --decode > .env
      - run:
          name: Install Esy
          command: sudo npm install -g esy

      - run:
          name: Install dependencies
          command: esy install

      - run:
          name: Build Server
          command: esy build

  deploy:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Decode Env File
          command: echo ${ENV_FILE} | base64 --decode > .env

      - run:
          name: Deploy container
          command: |
            git archive develop --format=tar.gz --output=server.tar.gz
            scp server.tar.gz ${DROPLET_USER}@${DROPLET_IP}:/server.tar.gz
            ssh ${DROPLET_USER}@${DROPLET_IP} "tar -xzf server.tar.gz && cd /server && docker-compose up"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy
